name: Workflows Sync

'on':
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # sync daily at 6:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Workflows Sync
        uses: wow-actions/workflows-sync@main
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          owner: _hyp3ri0n-ng
          workflows: .github/workflows/
          commit_message: "Sync workflow files from .github repo"